### ISSUE TITLE
Convert changed fields into string

### ISSUE THREAD

**Issue by ValeriyRCG** [pozil/pub-sub-api-node-client#1]
How would we go about changing the "changed fields" property items into strings? In the readme example and in events that I am getting the changed fields array only has a single string value of "0x80000000000000000000800000". I have tried converting this from hex to decimal and to string with no success in getting it into a readable format.

`....
"diffFields": [],
"changedFields": [
  "0x80000000000000000000800000"
]
....`

**Comment by pozil** [comment]
Hi @ValeriyRCG, weird coincidence but I was already investigating this. I'm in contact with the Pub Sub API team and they told me that the `changedFields` is a hexadecimal string that we need to convert to binary. We can then use the binary content as a bitmap to detect the fields that changed.
I'm working on implementing this in the client example, stay tuned.

**Comment by ValeriyRCG** [comment]
Thank you @pozil. I will also try to see if I can get this working on my end as well.

**Comment by pozil** [comment]
Hi @ValeriyRCG I just pushed an update with the proper parsing. I've requested a documentation update because it was not mentioned that the bitmap has to reversed for proper parsing.
The solution that I just contributed is functional for basic fields but I still need to get inputs from the product team to handle compound fields.

**Comment by pozil** [comment]
And I just added support for compound fields. Closing this issue now.
