### ISSUE TITLE
TypeError: encodedReplayId.readBigUInt64BE is not a function

### ISSUE THREAD

**Issue by alice-watershed** [pozil/pub-sub-api-node-client#50]
We have a long-running Salesforce Pub/Sub connection. Sometimes a few hours into the connection we suddenly start getting error messages stating “TypeError: encodedReplayId.readBigUInt64BE is not a function”. 

This is a message that is being received on the callbackType of `error`, although reading through the code it seems like it’s a regular `event` message that gets rerouted in the pubsub-api-client code to the `error` callbackType because it can’t parse the replayId. I can’t deterministically reproduce it (I’ve opened a separate Salesforce Pub/Sub connection to request the exact same events and it works fine). It seems to happen repeatedly for a period of time, and then stops happening for a period of time, and repeats.

<img width="1702" alt="image" src="https://github.com/user-attachments/assets/9287e124-b88e-4bf9-820a-8bad24ba2427">

**Comment by pozil** [comment]
Hi @alice-watershed thanks for reporting this issue.

I fixed the error reporting logic to show the proper error message that I intended to display in such a case:
> Failed to parse event with unknown replay ID (latest replay ID was xxxxxx)

This will also surface the underlying cause of the parsing error in the logs. However, I don't know what could cause an event to be sent without a replay ID. I have the feeling that the issue lies on the server side.

Can you update to the latest version (v5.0.3) and share the extra error info if this happens again?

**Comment by pozil** [comment]
Hi @alice-watershed I have good news regarding this issue: I was working on implementing batch event publishing and I figured out what was the root cause. This is happening because each `subscribe*` calls is duplicating internal gRPC event handlers instead of overwriting the ones defined in previous calls.

This is what you experienced in #52.

Then, what causes the “TypeError: encodedReplayId.readBigUInt64BE is not a function” error is that the replay ID has already been decoded by the first event handler. When it gets to the subsequent handlers, it's already decoded into a `number` type whereas the function expects a `Buffer` type (the original format received by the client).

I'll release a new version of the client shorty.
